from typing import Protocol, Iterator, List, Any
import pandas as pd
from .models import TableSchema, QualityIssue

class DatabaseConnector(Protocol):
    """Standard Interface for Database Connection"""
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def check_health(self) -> bool: ...
    def get_schema(self, table_name: str) -> TableSchema: ...
    def get_all_tables(self) -> List[str]: ...
    
    # Key: Mandatory requirement to return Iterator to support stream processing
    def fetch_data(self, query: str, chunk_size: int = 10000) -> Iterator[pd.DataFrame]: ...

class DataReader(Protocol):
    """Standard Interface for Data Reading (Supports Multi-source: DB / CSV / Parquet)"""
    def read(self, chunk_size: int = 50000) -> Iterator[pd.DataFrame]: ...
    def get_source_info(self) -> dict: ...

class DataWriter(Protocol):
    """Standard Interface for Data Writing"""
    def write(self, df: pd.DataFrame) -> None: ...
    def finalize(self) -> str: ...  # Returns success message

class QualityRule(Protocol):
    """Interface for Data Quality Inspection Strategy"""
    @property
    def name(self) -> str: ...
    
    def check(self, df: pd.DataFrame) -> List[QualityIssue]:
        """Returns a list of data anomalies List[QualityIssue]"""
        ...
